# Bun configuration file
[install]
# Use npm registry for package installation
registry = "https://registry.npmjs.org"
# Enable cache for faster installs
cache = true
# Automatically install peer dependencies
auto = "auto"
# Use binary lock file format
lockfile = "bun"

[run]
# Use bun runtime for scripts
bun = true

[test]
# Use bun's built-in test runner
# Coverage settings
coverage = true

[build]
# TypeScript compilation settings
target = "node"
# Enable source maps for debugging
sourcemap = "external"
