# Bun configuration file
[install]
# Use npm registry for package installation
registry = "https://registry.npmjs.org"
# Automatically install peer dependencies
auto = "auto"

[install.cache]
# Enable cache for faster installs
disable = false

[install.lockfile]
# Use binary lock file format
save = true
print = "yarn"

[run]
# Use bun runtime for scripts
bun = true

[test]
# Use bun's built-in test runner
# Coverage settings
coverage = true

[build]
# TypeScript compilation settings
target = "node"
# Enable source maps for debugging
sourcemap = "external"
