apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: repo-analyzer-ingress
  namespace: repo-analyzer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: '50m'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
    - hosts:
        - repo-analyzer.yourdomain.com
      secretName: repo-analyzer-tls
  rules:
    - host: repo-analyzer.yourdomain.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: repo-analyzer-backend-service
                port:
                  number: 3000
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: repo-analyzer-backend-service
                port:
                  number: 3000
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: repo-analyzer-backend-service
                port:
                  number: 3000
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: repo-analyzer-backend-service
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: repo-analyzer-frontend-service
                port:
                  number: 80
