apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unified-repo-analyzer-data-pvc
  namespace: unified-repo-analyzer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unified-repo-analyzer-logs-pvc
  namespace: unified-repo-analyzer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unified-repo-analyzer-backups-pvc
  namespace: unified-repo-analyzer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
